# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WCPMS
                                 A QGIS plugin
 WCPMS Plugin for QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-03
        git sha              : $Format:%H$
        copyright            : (C) 2025 by INPE
        email                : gabriel.sansigolo@inpe.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os


class Config:
    """Base configuration for global variables.

    :attribute BASE_DIR(str): Returns app root path.
    """

    BASE_DIR = os.path.abspath(os.path.dirname(__file__))

    WTSS_HOST = os.getenv("WTSS_HOST", "https://data.inpe.br/bdc/wtss/v4/")

    WCPMS_HOST = os.getenv("WCPMS_HOST", "https://data.inpe.br/bdc/wcpms/")

    # Available options browser, plotly, matplotlib & seaborn
    WCPMS_PLOT_OPTION = os.getenv("WCPMS_PLOT_OPTION", "seaborn")
